### ISSUE TITLE
Publish on Ansible galaxy

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#12]
Good "sign of quality" objective is to publish StackStorm roles on Ansible galaxy to get some more attention from the community.
At that point it should be tested/stable enough.
- [x] Register Ansible Galaxy account
- [ ] Polish, Refactor, Follow best practices
- [ ] Integration Tests #15 
- [ ] Ansible Galaxy Docs, Examples
- [ ] Decide: ship it as `stackstorm.st2` role or `st2`, `st2web`, `st2mistral`, `st2chatops` roles
- [x] ~Use Ansible Galaxy 3rd-party dependencies for `postgresql`, `rabbitmq`, `mongo`~ (We use our own roles now, but should leave an option for users to choose alternate external roles)

**Comment by ytjohn** [comment]
Relates to:

https://github.com/StackStorm/ansible-st2/issues/95
https://github.com/StackStorm/ansible-st2/issues/45

**Comment by ytjohn** [comment]
Under "Decide" I would recommend that you ship as "stackstorm.X". This lets you continue shipping your more common roles (nginx/postgresql/rabbitmq) under your name until you feel comfortable moving to any 3rd-party roles.

I would put that decision higher up, and register an account sooner rather than later. That way you can have the stackstorm username and stackstorm.<role name>, even if you don't list anything on galaxy.

Immediately after that, you should rename the roles in place. For example, if you register with the username "stackstorm", you would rename `roles/nginx` to `roles/stackstorm.nginx` and `roles/st2` to `roles/stackstorm.st2`.  Then you would update the playbook example to use the new names.

I would strongly encourage to do this step as early as possible. This gives those of us downloading the roles and dropping them into our `ext_roles` directory the ability to isolate them right away. Then, once you split the roles out into their own repos, they will already be named appropriately.

**Comment by armab** [comment]
Sounds like a good plan and we're thinking alike because we already started tagging some roles in internal infra with `stackstorm.role-name` namespace :+1: 

So I just connected existing all-in-one `ansible-st2` repo to the Galaxy: 
https://galaxy.ansible.com/StackStorm/stackstorm/

Sadly `StackStorm` is case sensitive as is, - Galaxy takes it from the GitHub org name (see https://groups.google.com/forum/#!msg/ansible-project/RkBTwc7MIS4/E1ac8OFPAAAJ). I'd like `stackstorm.` namespace more, comparing to `StackStorm.`

Renaming all the roles `st2web` -> `StackStorm.st2web` makes sense in a next `0.8.0` release, since it's a breaking change, thanks @ytjohn for the reminder! :+1:

**Comment by armab** [comment]
https://galaxy.ansible.com/StackStorm/stackstorm/
