### ISSUE TITLE
Add support for st2scheduler

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/ansible-st2#207]
In 3.0 `st2scheduler` will be a new service. Need to add support for this.

https://github.com/StackStorm/st2/pull/4382

**Comment by armab** [comment]
Since the absence of `st2scheduler` starting from `3.0dev` _really_ fails the build ([unstable is red](https://github.com/StackStorm/ansible-st2/pull/209)), this time need somehow to make sure that the update is version-dependent. Additionally should keep in mind corner cases with `dev`/`unstable` package repos.
