### ISSUE TITLE
Installation on EL8 reports failure due to passlib not installed

### ISSUE THREAD

**Issue by amanda11** [StackStorm/ansible-st2#312]
Since 29th May problems have been seen on installation with ansible and EL8. The ansible version in EPEL has moved to 5.x which installs python38.

Error reported:
```
       TASK [StackStorm.st2 : auth | Create htpasswd file] ****************************
       task path: /tmp/kitchen/roles/StackStorm.st2/tasks/auth.yml:34
       redirecting (type: modules) ansible.builtin.htpasswd to community.general.htpasswd
       An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'passlib'
       fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (passlib) on a4b87b2336f8's Python /bin/python3.8. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

The problem is that the playbooks install python3-passlib which is a python 3.6 passlib module. But Ansible 5.x uses python3.8. There is no RPM built at moment for python3.8 passlib, see https://bugzilla.redhat.com/show_bug.cgi?id=2087268

**Comment by amanda11** [comment]
Currently investigate if following workaround works

1. Install python36
2. Create a hosts file and set ansible_python_interpreter to /usr/local/bin/python3.6 for the EL8 machines
3. Run standard ansible-st2 playbooks.

**Comment by armab** [comment]
There are some hints in the `kitchen-ansible` about how to specify the Ansible inventory, maybe that'll help with the workaround:
https://github.com/neillturner/kitchen-ansible/blob/master/provisioner_options.md#ansible-inventory


On the other side, I understand our problem is with passlib dependency:
https://github.com/StackStorm/ansible-st2/blob/02b5ffbde1ce35666bf0c106b80659270c9c6000/roles/StackStorm.st2/vars/redhat_8.yml#L3

What if we'll try to install the `passlib` dependency from pip instead of using the OS package?
